basePath: /api/v1
definitions:
  db.User:
    properties:
      created_at:
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      email:
        type: string
      enabled:
        type: boolean
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      password:
        type: string
      updated_at:
        type: string
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
info:
  contact:
    email: nic.s.pearson@gmail.com
    name: API Support
  description: Swagger API documentation for the Golang Starter API.
  license:
    name: MIT
    url: https://github.com/nicolaspearson/go.api/blob/master/LICENSE
  termsOfService: http://swagger.io/terms/
  title: Golang Starter API
  version: "1.0"
paths:
  /users/{id}:
    get:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.User'
      security:
      - ApiKeyAuth: []
      summary: Retrieves the user identified by the provided ID
swagger: "2.0"
