dbName: api
dbUser: master
dbPassword: secret
dbHost: localhost
dbPort: 5432
environment: development
rabbitMqUsername: guest
rabbitMqPassword: secret
rabbitMqHost: localhost
rabbitMqVirtualHost: ""
releaseVersion: unknown
serverHost: localhost
serverPort: 3000
version: unknown
