name: "code"
on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/code.yaml"
      - ".github/workflows/publish.yaml"
      - "build/**"
      - "cmd/**"
      - "config/**"
      - "pkg/**"
      - "Dockerfile"
      - "go.mod"
      - "go.sum"
      - "Makefile"
  pull_request:
    paths:
      - ".github/workflows/code.yaml"
      - ".github/workflows/publish.yaml"
      - "build/**"
      - "cmd/**"
      - "config/**"
      - "pkg/**"
      - "Dockerfile"
      - "go.mod"
      - "go.sum"
      - "Makefile"

env:
  GITHUB_USER: nicolaspearson

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: install
        run: make go-install
      - name: build
        run: make go-build
      - name: test
        run: make go-test
  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2.3.4
      - name: Clean old release drafts
        run: hub release -f "%T (%S) %n" --include-drafts | grep " (draft)" | awk '{print $1}' | xargs --no-run-if-empty -t -n1 hub release delete
        env:
          GITHUB_USER: ${{ env.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        uses: minddocdev/mou-release-action@master
        with:
          draft: true
          prerelease: false
          templatePath: RELEASE_DRAFT/default.md
          token: ${{ secrets.GITHUB_TOKEN }}
